// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  default: dynamic(() => import("./Default")),
  rich_text: dynamic(() => import("./RichText")),
};
